version: '3'

services:
  backend:
    build:
      context: ./backend
    environment:
      - ALLOWED_HOSTS=simulator.salt.ac.za
      - DEBUG=0

  frontend:
    build:
      context: ./frontend
    environment:
      - VITE_BACKEND_BASE_URL=

  router:
    build:
      context: ./router
    depends_on:
      - backend
    ports:
      - "7999:80"
