version: '3'

services:
  backend:
    build:
      context: ./backend
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  frontend:
    build:
      context: ./frontend

  nginx:
    build:
      context: ./nginx
    depends_on:
      - backend
    ports:
      - "7999:80"
