version: '3'

services:
  web:
    build:
      context: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    volumes:
      - ./data_sheets:/app/backend/data_sheets
