FROM python:3.10 AS build

WORKDIR /documentation

COPY backend/requirements.txt .

RUN pip install -r requirements.txt

COPY documentation/mkdocs.yml .
COPY documentation/docs docs
COPY backend ../backend
RUN mkdocs build

FROM nginx:1.25

# Copy the built documentation.
COPY --from=build /documentation/site /documentation/docs

# Create the server configuration.
RUN rm /etc/nginx/conf.d/default.conf
COPY deployment/nginx-documentation.conf /etc/nginx/conf.d/

